sudo: required
dist: trusty

arch:
  - amd64
  - arm64

language: go
go:
  - 1.10.x
go_import_path: github.com/GoogleContainerTools/container-structure-test

script:
  - ./hack/.gofmt.sh
  - make
  - ./tests/structure_test_tests.sh
